// Code generated by "rxabi -type IntentType"; DO NOT EDIT.
// This file should be tracked by the version manager

export enum IntentType {
  NoIntent = 0,
  Click = 1,
  DoubleClick = 2,
  DragStart = 3,
  DragOver = 4,
  DragEnd = 5,
  Drop = 6,
  EscPress = 7,
  Scroll = 8,
  Filter = 9,
  Change = 10,
  Blur = 11,
  ChangeView = 12,
  ManifestChange = 13,
  ShowDebugMenu = 14,
  CellSizeChange = 15,
  Submit = 16,
  Seppuku = 17,
}
