// Code generated by "rxabi -type IntentType"; DO NOT EDIT.
// This file should be tracked by the version manager

export enum IntentType {
	NoIntent= 0,
	Click= 1,
	DoubleClick= 2,
	DragStart= 3,
	DragOver= 4,
	DragEnd= 5,
	Drop= 6,
	EscPress= 7,
	Scroll= 8,
	Filter= 9,
	Change= 10,
	KeyUp= 11,
	Blur= 12,
	ChangeView= 13,
	ManifestChange= 14,
	ShowDebugMenu= 15,
	CellSizeChange= 16,
	Submit= 17,
	Seppuku= 18,
}